version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  commit-message:
    prefix: chore(deps)
  labels:
  - dependencies
  - python
  reviewers:
  - quentin
  groups:
    development:
      patterns:
      - pytest*
      - black
      - isort
      - flake8*
      - mypy*
      - bandit*
      - pre-commit
      - coverage*
      update-types:
      - minor
      - patch

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 3
  commit-message:
    prefix: chore(deps)
  labels:
  - dependencies
  - github-actions
